require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookSignupsController do

  # This should return the minimal set of attributes required to create a valid
  # BookSignup. As you add validations to BookSignup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "launcher_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookSignupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all book_signups as @book_signups" do
      book_signup = BookSignup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:book_signups).should eq([book_signup])
    end
  end

  describe "GET show" do
    it "assigns the requested book_signup as @book_signup" do
      book_signup = BookSignup.create! valid_attributes
      get :show, {:id => book_signup.to_param}, valid_session
      assigns(:book_signup).should eq(book_signup)
    end
  end

  describe "GET new" do
    it "assigns a new book_signup as @book_signup" do
      get :new, {}, valid_session
      assigns(:book_signup).should be_a_new(BookSignup)
    end
  end

  describe "GET edit" do
    it "assigns the requested book_signup as @book_signup" do
      book_signup = BookSignup.create! valid_attributes
      get :edit, {:id => book_signup.to_param}, valid_session
      assigns(:book_signup).should eq(book_signup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BookSignup" do
        expect {
          post :create, {:book_signup => valid_attributes}, valid_session
        }.to change(BookSignup, :count).by(1)
      end

      it "assigns a newly created book_signup as @book_signup" do
        post :create, {:book_signup => valid_attributes}, valid_session
        assigns(:book_signup).should be_a(BookSignup)
        assigns(:book_signup).should be_persisted
      end

      it "redirects to the created book_signup" do
        post :create, {:book_signup => valid_attributes}, valid_session
        response.should redirect_to(BookSignup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved book_signup as @book_signup" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookSignup.any_instance.stub(:save).and_return(false)
        post :create, {:book_signup => { "launcher_id" => "invalid value" }}, valid_session
        assigns(:book_signup).should be_a_new(BookSignup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookSignup.any_instance.stub(:save).and_return(false)
        post :create, {:book_signup => { "launcher_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested book_signup" do
        book_signup = BookSignup.create! valid_attributes
        # Assuming there are no other book_signups in the database, this
        # specifies that the BookSignup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BookSignup.any_instance.should_receive(:update).with({ "launcher_id" => "1" })
        put :update, {:id => book_signup.to_param, :book_signup => { "launcher_id" => "1" }}, valid_session
      end

      it "assigns the requested book_signup as @book_signup" do
        book_signup = BookSignup.create! valid_attributes
        put :update, {:id => book_signup.to_param, :book_signup => valid_attributes}, valid_session
        assigns(:book_signup).should eq(book_signup)
      end

      it "redirects to the book_signup" do
        book_signup = BookSignup.create! valid_attributes
        put :update, {:id => book_signup.to_param, :book_signup => valid_attributes}, valid_session
        response.should redirect_to(book_signup)
      end
    end

    describe "with invalid params" do
      it "assigns the book_signup as @book_signup" do
        book_signup = BookSignup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookSignup.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_signup.to_param, :book_signup => { "launcher_id" => "invalid value" }}, valid_session
        assigns(:book_signup).should eq(book_signup)
      end

      it "re-renders the 'edit' template" do
        book_signup = BookSignup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookSignup.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_signup.to_param, :book_signup => { "launcher_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested book_signup" do
      book_signup = BookSignup.create! valid_attributes
      expect {
        delete :destroy, {:id => book_signup.to_param}, valid_session
      }.to change(BookSignup, :count).by(-1)
    end

    it "redirects to the book_signups list" do
      book_signup = BookSignup.create! valid_attributes
      delete :destroy, {:id => book_signup.to_param}, valid_session
      response.should redirect_to(book_signups_url)
    end
  end

end
