require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookLaunchersController do

  # This should return the minimal set of attributes required to create a valid
  # BookLauncher. As you add validations to BookLauncher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "book_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookLaunchersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all book_launchers as @book_launchers" do
      book_launcher = BookLauncher.create! valid_attributes
      get :index, {}, valid_session
      assigns(:book_launchers).should eq([book_launcher])
    end
  end

  describe "GET show" do
    it "assigns the requested book_launcher as @book_launcher" do
      book_launcher = BookLauncher.create! valid_attributes
      get :show, {:id => book_launcher.to_param}, valid_session
      assigns(:book_launcher).should eq(book_launcher)
    end
  end

  describe "GET new" do
    it "assigns a new book_launcher as @book_launcher" do
      get :new, {}, valid_session
      assigns(:book_launcher).should be_a_new(BookLauncher)
    end
  end

  describe "GET edit" do
    it "assigns the requested book_launcher as @book_launcher" do
      book_launcher = BookLauncher.create! valid_attributes
      get :edit, {:id => book_launcher.to_param}, valid_session
      assigns(:book_launcher).should eq(book_launcher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BookLauncher" do
        expect {
          post :create, {:book_launcher => valid_attributes}, valid_session
        }.to change(BookLauncher, :count).by(1)
      end

      it "assigns a newly created book_launcher as @book_launcher" do
        post :create, {:book_launcher => valid_attributes}, valid_session
        assigns(:book_launcher).should be_a(BookLauncher)
        assigns(:book_launcher).should be_persisted
      end

      it "redirects to the created book_launcher" do
        post :create, {:book_launcher => valid_attributes}, valid_session
        response.should redirect_to(BookLauncher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved book_launcher as @book_launcher" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookLauncher.any_instance.stub(:save).and_return(false)
        post :create, {:book_launcher => { "book_id" => "invalid value" }}, valid_session
        assigns(:book_launcher).should be_a_new(BookLauncher)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookLauncher.any_instance.stub(:save).and_return(false)
        post :create, {:book_launcher => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested book_launcher" do
        book_launcher = BookLauncher.create! valid_attributes
        # Assuming there are no other book_launchers in the database, this
        # specifies that the BookLauncher created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BookLauncher.any_instance.should_receive(:update).with({ "book_id" => "1" })
        put :update, {:id => book_launcher.to_param, :book_launcher => { "book_id" => "1" }}, valid_session
      end

      it "assigns the requested book_launcher as @book_launcher" do
        book_launcher = BookLauncher.create! valid_attributes
        put :update, {:id => book_launcher.to_param, :book_launcher => valid_attributes}, valid_session
        assigns(:book_launcher).should eq(book_launcher)
      end

      it "redirects to the book_launcher" do
        book_launcher = BookLauncher.create! valid_attributes
        put :update, {:id => book_launcher.to_param, :book_launcher => valid_attributes}, valid_session
        response.should redirect_to(book_launcher)
      end
    end

    describe "with invalid params" do
      it "assigns the book_launcher as @book_launcher" do
        book_launcher = BookLauncher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookLauncher.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_launcher.to_param, :book_launcher => { "book_id" => "invalid value" }}, valid_session
        assigns(:book_launcher).should eq(book_launcher)
      end

      it "re-renders the 'edit' template" do
        book_launcher = BookLauncher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookLauncher.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_launcher.to_param, :book_launcher => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested book_launcher" do
      book_launcher = BookLauncher.create! valid_attributes
      expect {
        delete :destroy, {:id => book_launcher.to_param}, valid_session
      }.to change(BookLauncher, :count).by(-1)
    end

    it "redirects to the book_launchers list" do
      book_launcher = BookLauncher.create! valid_attributes
      delete :destroy, {:id => book_launcher.to_param}, valid_session
      response.should redirect_to(book_launchers_url)
    end
  end

end
